name: Cypress Tests

on:
  workflow_dispatch:

jobs:
  cypress-run:
    runs-on: node20
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      with:  
        repository: mendi-J/Technical-Exercise
        ref: master

    - name: Install Dependencies
      run: npm install

    - name: Run Cypress Tests
      run: npm run cypress:run
