name: Cypress Tests

on:
  workflow_dispatch:

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.11.1 ]
    steps:
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - name: Checkout Repository
      uses: actions/checkout@v2
      with:  
        repository: mendi-J/Technical-Exercise
        ref: main

    - name: Install Dependencies
      run: npm install

    - name: Run Cypress Tests
      run: npm run cypress:run
